### ISSUE TITLE
When using raincloud_plot in matlab for data that are in [0 1] the histogram is too wide

### ISSUE THREAD

**Issue by edgarbc** [RainCloudPlots/RainCloudPlots#12]
Hi there,

thanks a lot for sharing RainCloudPlots, it is great! I just tried the matlab version and my data are in [0 1], when I use raincloud_plot to visualize this, the histogram is way wider than the population. I scaled my data to be [10 20] and the cloud is properly displayed. I also tried to scaled the data from the tutorial into [0 1] and the same problem appears.

Am I missing something? Thanks!

**Comment by TomRhysMarshall** [comment]
Hi Edgar,

Thanks for reporting this. I just reproduced the error - I think it is to do with the default value of the 'bandwidth' parameter.

Can you please try, instead of scaling your data, explicitly plotting a few times with a range of different bandwidths? I.e., adding ... 
**'bandwidth', some_value)**  (eg 0.01, 0.1, 1, 10)
to the end of your call to raincloud_plot, just to let me know if that changes/fixes things?

Thanks a lot!

Best,
Tom

**Comment by TomRhysMarshall** [comment]
I went ahead and fixed it. Would be v.greatful if you could try again and see if the problem is solved. Thanks!

**Comment by edgarbc** [comment]
Hi guys,
sorry for the very slooooooow reply. I just tried the new version and confirmed that the problem is fixed.

Thanks!
